version: "3.4"

services:
  app:
    image: dockerexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules/
      - /usr/src/app/bin/
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - ts-express-network
    command: yarn dev

  mysql:
    image: mysql:8.0
    env_file: ./mysql/mysql.env
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - my_volume:/var/lib/mysql
    networks:
      - ts-express-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  ts-express-network:

volumes:
  my_volume:
